spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:deepple}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        generate_statistics: true
        format_sql: ${JPA_FORMAT_SQL:false}
        jdbc:
          timezone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history

  lifecycle:
    timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

logging:
  level:
    root: info

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  tomcat:
    max-http-form-post-size: 50MB

jwt:
  secret: ${JWT_SECRET:this-is-secret-key-value-at-least-128-bytes}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800}  # 30분
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600}  # 2주

auth:
  refresh-token-cookie:
    name: refresh_token
    max-age: 2419200  # 4주
    path: /
    same-site: None
    secure: true
    http-only: true
  prefix-code: ${AUTH_PREFIX_CODE:008008}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_UI_ENABLED:false}

payment:
  app-store:
    key-id: ${APP_STORE_KEY_ID:key-id}
    private-key-string: ${APP_STORE_PRIVATE_KEY_STRING:private-key-string}
    issuer-id: ${APP_STORE_ISSUER_ID:issuer-id}
    environment: ${APP_STORE_ENVIRONMENT:Production}
    bundle-id: ${APP_STORE_BUNDLE_ID:bundle-id}
    app-apple-id: ${APP_STORE_APP_APPLE_ID:0000000000}
    root-ca-paths: ${APP_STORE_ROOT_CA_G2_PATH:/etc/certs/appstore/AppleRootCA-G2.pem}, ${APP_STORE_ROOT_CA_G3_PATH:/etc/certs/appstore/AppleRootCA-G3.pem}
    base-url: ${APP_STORE_BASE_URL:https://api.storekit.itunes.apple.com}

bizgo:
  api-url: ${BIZGO_API_URL:api-url}
  client-id: ${BIZGO_CLIENT_ID:client-id}
  client-password: ${BIZGO_CLIENT_PASSWORD:client_password}
  from-phone-number: ${BIZGO_FROM_PHONE_NUMBER:from-phone-number}

scheduler:
  cron: "0 0 0 * * *"

management:
  server:
    port: 8081
